namespace URMS.Application.DTOs.Requests;

public record UniversityRequestResponseDto(
    int Id,
    string StudentId,
    string StudentNameAr,
    string StudentNameEn,
    string? UniversityCode,
    int? FormDefinitionId,
    string? FormTitleAr,
    string? FormTitleEn,
    string Status,
    string StatusAr,
    string StatusEn,
    string NextAction,
    string NextActionEn,
    bool CanWithdraw,
    bool CanConfirm,
    Dictionary<string, string>? AdditionalData,
    string? AdvisorId,
    string? AdvisorName,
    string? RejectionReason,
    string? ExternalAdministrationEmail,
    bool IsExternalAdministrationNotificationSent,
    DateTime? ExternalAdministrationSentAt,
    DateTime? ExternalAdministrationOtpExpiresAt,
    DateTime? ExternalAdministrationRespondedAt,
    string? ExternalAdministrationResponseNotes,
    DateTime CreatedAt,
    DateTime? ApprovedAt,
    DateTime? CompletedAt,
    List<RequestHistoryLogDto>? HistoryLogs = null
);
